/**
 * Static job pool — India tech market (Phase 1 seed data).
 * Replace / augment with live DB or aggregator in Phase 2.
 */

export type JdTrust = "high" | "medium" | "low";
export type WorkMode = "remote" | "hybrid" | "onsite";

export interface Job {
  id: string;
  title: string;
  company: string;
  logo: string;           // emoji fallback
  location: string;
  mode: WorkMode;
  exp: string;            // e.g. "2–4 yrs"
  salary: string;         // e.g. "₹18–26 LPA"
  skills: string[];       // required skills (lowercase, matches MARKET_SKILLS)
  postedDays: number;     // days ago
  applicants: number;
  trust: JdTrust;
  verified: boolean;
  ghost: boolean;         // suspected ghost job
  avgResponseDays: number;
  replyRate: number;      // 0–100
  jdText: string;         // full JD text for matching
  applyUrl?: string;      // direct application link
}

const JOBS: Job[] = [
  {
    id: "rp-sde2",
    title: "Senior Full Stack Engineer",
    company: "Razorpay",
    logo: "🦓",
    location: "Bangalore",
    mode: "hybrid",
    exp: "3–5 yrs",
    salary: "₹18–26 LPA",
    skills: ["react", "node.js", "postgresql", "typescript", "docker", "aws"],
    postedDays: 0,
    applicants: 12,
    trust: "high",
    verified: true,
    ghost: false,
    avgResponseDays: 2,
    replyRate: 78,
    jdText: "We are looking for a Senior Full Stack Engineer with strong React and Node.js skills. Experience with PostgreSQL, TypeScript, Docker and AWS required. System design knowledge is a plus.",
  },
  {
    id: "fk-sde2",
    title: "SDE-2 · Backend (Node.js)",
    company: "Flipkart",
    logo: "🛒",
    location: "Bangalore",
    mode: "onsite",
    exp: "2–4 yrs",
    salary: "₹22–30 LPA",
    skills: ["node.js", "postgresql", "rest api", "redis", "kubernetes", "microservices"],
    postedDays: 1,
    applicants: 48,
    trust: "high",
    verified: true,
    ghost: false,
    avgResponseDays: 3,
    replyRate: 65,
    jdText: "Flipkart is hiring SDE-2 for backend systems. Strong Node.js, PostgreSQL, Redis, REST API, Kubernetes and microservices experience required.",
  },
  {
    id: "gw-fsd",
    title: "Full Stack Developer",
    company: "Groww",
    logo: "🚀",
    location: "Bangalore · Remote",
    mode: "remote",
    exp: "2–5 yrs",
    salary: "₹15–20 LPA",
    skills: ["react", "typescript", "graphql", "redis", "aws"],
    postedDays: 3,
    applicants: 94,
    trust: "medium",
    verified: false,
    ghost: false,
    avgResponseDays: 5,
    replyRate: 50,
    jdText: "Groww is looking for a Full Stack Developer with React, TypeScript, GraphQL, Redis and AWS skills.",
  },
  {
    id: "sw-fe",
    title: "Frontend Engineer (React)",
    company: "Swiggy",
    logo: "🍜",
    location: "Bangalore",
    mode: "hybrid",
    exp: "1–3 yrs",
    salary: "₹12–18 LPA",
    skills: ["react", "javascript", "typescript", "css", "html", "webpack"],
    postedDays: 2,
    applicants: 135,
    trust: "high",
    verified: true,
    ghost: false,
    avgResponseDays: 4,
    replyRate: 60,
    jdText: "We need a Frontend Engineer with strong React, JavaScript, TypeScript, CSS, HTML and Webpack skills to join our consumer product team.",
  },
  {
    id: "ph-sde",
    title: "Software Engineer · Full Stack",
    company: "PhonePe",
    logo: "📱",
    location: "Bangalore",
    mode: "onsite",
    exp: "2–4 yrs",
    salary: "₹20–28 LPA",
    skills: ["java", "react", "postgresql", "aws", "docker", "microservices"],
    postedDays: 4,
    applicants: 67,
    trust: "high",
    verified: true,
    ghost: false,
    avgResponseDays: 3,
    replyRate: 72,
    jdText: "PhonePe is hiring for Full Stack Software Engineer. Required: Java, React, PostgreSQL, AWS, Docker and microservices architecture.",
  },
  {
    id: "cred-fe",
    title: "Senior Frontend Developer",
    company: "CRED",
    logo: "💳",
    location: "Bangalore",
    mode: "hybrid",
    exp: "3–6 yrs",
    salary: "₹25–35 LPA",
    skills: ["react", "typescript", "next.js", "graphql", "tailwind", "webpack"],
    postedDays: 5,
    applicants: 89,
    trust: "high",
    verified: true,
    ghost: false,
    avgResponseDays: 6,
    replyRate: 55,
    jdText: "CRED is looking for a Senior Frontend Developer with React, TypeScript, Next.js, GraphQL, Tailwind CSS and Webpack expertise.",
  },
  {
    id: "meesho-be",
    title: "Backend Engineer (Python)",
    company: "Meesho",
    logo: "🛍️",
    location: "Bangalore",
    mode: "hybrid",
    exp: "2–5 yrs",
    salary: "₹18–24 LPA",
    skills: ["python", "django", "postgresql", "redis", "aws", "docker"],
    postedDays: 2,
    applicants: 55,
    trust: "high",
    verified: true,
    ghost: false,
    avgResponseDays: 4,
    replyRate: 68,
    jdText: "Meesho needs a Backend Engineer with Python, Django, PostgreSQL, Redis, AWS and Docker. Experience with high-scale systems preferred.",
  },
  {
    id: "zepto-fsd",
    title: "Full Stack Engineer",
    company: "Zepto",
    logo: "⚡",
    location: "Mumbai · Remote",
    mode: "remote",
    exp: "2–4 yrs",
    salary: "₹16–22 LPA",
    skills: ["react", "node.js", "typescript", "mongodb", "aws"],
    postedDays: 1,
    applicants: 32,
    trust: "high",
    verified: true,
    ghost: false,
    avgResponseDays: 2,
    replyRate: 80,
    jdText: "Zepto is hiring a Full Stack Engineer with React, Node.js, TypeScript, MongoDB and AWS skills for our fast-growing platform.",
  },
  {
    id: "juspay-sde",
    title: "Software Engineer · Payments",
    company: "Juspay",
    logo: "💸",
    location: "Bangalore",
    mode: "hybrid",
    exp: "2–5 yrs",
    salary: "₹18–26 LPA",
    skills: ["java", "postgresql", "rest api", "microservices", "docker", "aws"],
    postedDays: 6,
    applicants: 44,
    trust: "high",
    verified: true,
    ghost: false,
    avgResponseDays: 5,
    replyRate: 62,
    jdText: "Juspay seeks a Software Engineer for payments infrastructure. Java, PostgreSQL, REST APIs, microservices, Docker and AWS required.",
  },
  {
    id: "unverified-ghost",
    title: "React Developer — 10 yrs exp",
    company: "TechRecruiter Pvt Ltd",
    logo: "🏢",
    location: "Bangalore / Remote",
    mode: "remote",
    exp: "10 yrs",
    salary: "Not disclosed",
    skills: ["react"],
    postedDays: 18,
    applicants: 0,
    trust: "low",
    verified: false,
    ghost: true,
    avgResponseDays: 99,
    replyRate: 5,
    jdText: "React Developer required. 10 years experience. Apply now.",
  },
];

export default JOBS;
